version: '3'
services:
  tomcat:
    image: tomcat:9
    container_name: 'tomcat'
    environment:
      TZ: "Asia/Seoul"
      JDBC_URL: jdbc:mysql://db:3306/jca
      JDBC_USER: leehg
      JDBC_PASS: 789gagul
    links:
      - db
      - redis
    ports:
      - '5126:5126'
    volumes:
      - 'tomcat_data:/usr/local/tomcat/webapps/'
    restart:
      always
      
volumes:
  tomcat_data:
    driver: local