version: '3'
services:
  tomcat:
    image: tomcat:9
    container_name: 'tomcat'
    ports:
      - '5126:5126'
    volumes:
      - 'tomcat_data:/usr/local/tomcat/webapps/'
    restart:
      always
      
volumes:
  tomcat_data:
    driver: local